name: Format

on: [push, pull_request]

env:
  SCARB_VERSION: 2.11.3

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: ${{ env.SCARB_VERSION }}
      - name: Check cairo format
        run: scarb fmt --check